* Assignment 2 - data types

Read sections 1.2 (1.2.1 through 1.2.5) from the [[https://introcs.cs.princeton.edu/java/10elements/][text book]]. 

This section deals with basic data types. Java differs from Python and
Javascript in that you have to declare variables before you use them
and in that declaration tell the compiler what type of data they'll
represent. 

For example in Python, if you wanted to use a variable ~inval~ to hold
an integer value and ~doubval~ a floating point number you could just
write:

#+begin_src python
intval = 5
doubval = 123.45
#+end_src

whereas in Java you have to first declare the variables and then
assign them:

#+begin_src java
int intval;
double doubval;

intval = 5;
doubval = 123.45
#+end_src

You can though combine the steps:

#+begin_src java
int intval = 5;
double doubval = 123.45;
#+end_src

Read the chapter for details. You can also find more information in
the other supplemental materials linked on the prework page.

Choose three of the exercises from the chapter and write programs to
solve them. Note that the solutions are already published in the
book. Attempt them without looking at the solutions first but feel
free to look at solutions to other exercises for assistance.

Add the ~.java~ files for your three solutions to the assignment repos
under a folder named ~pre02~ and push them up to GitHub.

